### PR TITLE
add .env file so VSCode autocomplete functions work

### PR DESCRIPTION
**Pull request by irm-codebase**
Added an `.env` file pointing `PYTHONPATH` to `./src` so that VSCode can perform autocomplete functions for our code.

Small quality of life stuff.

### CODE REVIEW

**Comment by brynpickering** [comment]
Not sure what problem you're trying to solve here. If you follow the development install instructions and then link the mamba env to `Python: Select Interpreter` in VSCode, you get autocomplete. Example:

https://github.com/calliope-project/calliope-pathways/assets/17178478/97488b82-c240-4d04-ab9e-8a494dc07862

**Comment by irm-codebase** [comment]
This is quite odd... I swear it was not working before. 
It may be related to some issues that VSCode has been having with miniforge (https://github.com/microsoft/vscode-python/issues/22918), sometimes it refuses to activate the environment even after specifying it.

I'll close the pull request.

**Comment by brynpickering** [comment]
Interesting. I have this duplication issue but then I don't use the inbuilt vscode debugger so haven't had to deal with its ability to keep track of the environment correctly when debugging...

**Comment by irm-codebase** [comment]
What do you use as a debugger instead? This issue is completely breaking debug functionalities on my end, and I cannot test some things on the toy model :(

**Pull request closed without merging**
